version: ~> 1.0

os:
    - linux

dist:
    - xenial

language: python
python:
    - "3.8"

before_install:
    - pip install poetry
install:
    - poetry install

script:
    - poetry run pytest

before_deploy:
    - poetry config pypi-token.pypi $PYPI_PASSWORD
deploy:
    provider: script
    script: poetry publish --build