version: ~> 1.0

os:
    - linux

dist:
    - xenial

language: python
python:
    - "3.8"

before_install:
    - pip install poetry
install:
    - poetry install --no-interaction

script:
    - poetry run pytest

before_deploy:
    - poetry config pypi-token.pypi $PYPI_PASSWORD
deploy:
    provider: script
    script: |
        bumpversion --verbose patch
        poetry publish --build --no-interaction
        git -c user.name='travis' -c user.email='travis@travis-ci.com'
        git remote add origin-pages https://${GH_TOKEN}@github.com/MVSE-outreach/resources.git > /dev/null 2>&1