name: imagesearch

on:
  push:
  pull_request:
  release:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Retrieve cache dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-build-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Test
      run: |
        poetry run pytest

    - name: debug
      run: |
        env
        echo ${{ github.ref }}


