name: build

on:
  push:
  pull_request:
  release:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Test
      run: |
        poetry run pytest

    - name: Cut release
      run: |
        env
