name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config cache-dir .poetry_cache

    - name: Retrieve project cache dependencies
      uses: actions/cache@v2
      with:
        path: .poetry_cache
        key: ${{ runner.os }}-build-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install project dependencies
      run: |
        poetry install

    - name: Unit test
      run: |
        poetry run pytest --cov=imagesearch

    - name: Format check
      run: |
        poetry run black imagesearch tests --check

    - name: Lint
      run: |
        poetry run pylint imagesearch tests -E

    - name: Type check
      run: |
        poetry run  mypy imagesearch tests

    - name: Upload Coverage
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        poetry run coveralls

    - name: Create GH Release
      if: startswith(github.ref, 'refs/tags/v')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Release of 0.4.1
        # the above line is updated automatically with bumpversion. do not change it!
        draft: false
        prerelease: false

    - name: Publish to PyPI
      if: startswith(github.ref, 'refs/tags/v')
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry config pypi-token.pypi $PYPI_TOKEN
        poetry publish --build


